name: Build and Upload Packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-deb:
    name: Build Debian Package
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper meson python3-setuptools dh-make desktop-file-utils gtk-update-icon-cache
          sudo apt-get install -y \
            appstream \
            appstream-util \
            debhelper-compat \
            desktop-file-utils \
            gjs \
            gobject-introspection \
            hicolor-icon-theme \
            libgirepository1.0-dev \
            libglib2.0-dev-bin \
            libgtk-3-dev \
            libx11-dev \
            meson \
            node-babel-loader \
            nodejs \
            npm

      - name: Build .deb package
        run: |
          DPKG_DEB_COMPRESSOR_TYPE=xz dpkg-buildpackage -us -uc -nc
          mv ../*.deb .

      - name: Upload .deb as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: "*.deb"

      - name: Upload .deb to GitHub Release (only for releases)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: "*.deb"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}